### ISSUE TITLE
JSON Decode Error - Char 4319

### ISSUE THREAD

**Issue by theMoe** [stefan2200/TWB#119]
Hi,

after updating the factor of delay to 10 and the seconds to 606, I see this error, when I try to start the bot. Any ideas?

```
Traceback (most recent call last):
  File "/Users/user/Documents/GitHub/TWB/twb.py", line 487, in <module>
    main()
  File "/Users/user/Documents/GitHub/TWB/twb.py", line 441, in main
    check_update()
  File "/Users/user/Documents/GitHub/TWB/core/updater.py", line 30, in check_update
    parsed = json.load(fp=running_cf)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 159 column 2 (char 4319)
```

**Comment by chris7-dell** [comment]
i have the same problem

**Comment by chris7-dell** [comment]
Let 10 min to try and do restart
