### ISSUE TITLE
Error during attack

### ISSUE THREAD

**Issue by emajju** [stefan2200/TWB#14]
Log shows 
```
2022-01-03 19:56:17 - Reports - DEBUG - This is the newest? 2022-01-03 17:57:01
I crashed :(   cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "twb.py", line 380, in <module>
    t.start()
  File "twb.py", line 374, in start
    self.run()
  File "twb.py", line 315, in run
    vil.run(config=config, first_run=vnum == 1)
  File "/home/main/twb/game/village.py", line 441, in run
    self.attack.run()
  File "/home/main/twb/game/attack.py", line 63, in run
    out_res = self.send_farm(target, template)
  File "/home/main/twb/game/attack.py", line 80, in send_farm
    cached = self.can_attack(vid=target["id"], clear=False)
  File "/home/main/twb/game/attack.py", line 280, in can_attack
    res_left, res = self.repman.has_resources_left(vid)
TypeError: cannot unpack non-iterable NoneType object
```
After 3 times, scripts is stopping

**Comment by stefan2200** [comment]
Hi, this is probably caused with old reports not being compatible with the current version. I created a hotfix to solve this issue. Can you check if this fixes your crash?

**Comment by emajju** [comment]
Works fine now :)
