### ISSUE TITLE
Issues after restarting

### ISSUE THREAD

**Issue by siveti** [stefan2200/TWB#26]
Traceback (most recent call last):
  File "C:\Users\mee\OneDrive\Pulpit\TWB-master\twb.py", line 374, in <module>
    t.start()
  File "C:\Users\mee\OneDrive\Pulpit\TWB-master\twb.py", line 368, in start
    self.run()
  File "C:\Users\mee\OneDrive\Pulpit\TWB-master\twb.py", line 215, in run
    config = self.config()
  File "C:\Users\mee\OneDrive\Pulpit\TWB-master\twb.py", line 118, in config
    config = json.load(f, object_pairs_hook=collections.OrderedDict)
  File "C:\Users\mee\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\mee\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "C:\Users\mee\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\mee\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 109 column 5 (char 2984)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mee\OneDrive\Pulpit\TWB-master\twb.py", line 376, in <module>
    t.wrapper.reporter.report(0, "TWB_EXCEPTION", str(e))
AttributeError: 'NoneType' object has no attribute 'reporter'

**Comment by siveti** [comment]
\TWB-master\twb.py", line 377
    pl_auth = 10e49509da8a:c09320a63cb835ff9f2ea94dfd57c5f28596d6fa1295ac6cab2803dd42528dcc;
                     ^
SyntaxError: invalid decimal literal

**Comment by stefan2200** [comment]
It looks like your session file (`cache/session.json`) is broken, deleting it and restarting the bot will probably fix the issue

**Comment by siveti** [comment]
It didnt help

**Comment by MAHardo** [comment]
I am encountering the same problem, which is why I have not been able to connect the bot once. Is there already any solution available?
