### ISSUE TITLE
Maybe a User-Problem.

### ISSUE THREAD

**Issue by DemonicLevy** [stefan2200/TWB#37]
hey, and sorry for this Noob-Question, but how can i start thenew website with the Link http://127.0.0.1:5000/ This link is not working in my Browser (Chrome). maybe i just didnt understand something. 
The bot is to use in the Virtual Studio Programm, so did i use him.
again, sorry for the issue, maybe it will be very easy to answer it. 
Also i cant see if the bot is realy working, just like in an issue that was closed is there only the output of the Troop manager. 
And the Queue isnt growing. 

thank you very much! 
Levy

**Comment by stefan2200** [comment]
Hey man,

I'm just guessing but it looks like the web script is not running yet (separate part from the bot).
Since you are running VS code it should be pretty easy to start it, apart from the bot you need to start the webmanager script separately.

If you open the webmanager folder you need to manually start the web interface by also starting that script. If you run `server.py` the web interface should start :)

And I have no idea if the bot is really working, it is pure Python without any kind of telemetry so if you think it really won' t start please let me know (and include the console output) so I might be able to troubleshoot.

**Comment by DemonicLevy** [comment]
This is the Copy/Paste friendly version of the traceback.

Traceback (most recent call last):
  File "C:\Users\ricos\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\ricos\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\ricos\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ricos\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ricos\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ricos\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\ricos\OneDrive\Dokumente\GitHub\TWB\webmanager\server.py", line 217, in get_home
    return render_template('bot.html', data=sync(), session=session)
  File "c:\Users\ricos\OneDrive\Dokumente\GitHub\TWB\webmanager\server.py", line 132, in sync
    reports = DataReader.cache_grab("reports")
  File "c:\Users\ricos\OneDrive\Dokumente\GitHub\TWB\webmanager\utils.py", line 13, in cache_grab
    for existing in os.listdir(c_path):
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: '../cache\\reports'




thats the console output if i want to visit the server
thx for answering this fast !!

**Comment by DemonicLevy** [comment]
maybe it could be, that the bot is running particulary on linux ? / and \ could be the problem. A friend told me it coud be this problem

**Comment by stefan2200** [comment]
Fixed in current version of the bot, verified on Windows, Linux and Mac
