### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by MAHardo** [stefan2200/TWB#86]
Hi, I get this error when I try to run server.py after I upgraded the bot today:

`(base) C:\Users\...\Downloads\TWB-master\webmanager>python server.py
Traceback (most recent call last):
  File "C:\Users\...\Downloads\TWB-master\webmanager\server.py", line 8, in <module>
    from webmanager.helpfile import help_file, buildings
ModuleNotFoundError: No module named 'webmanager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\...\Downloads\TWB-master\webmanager\server.py", line 12, in <module>
    from utils import DataReader, BotManager, MapBuilder, BuildingTemplateManager
  File "C:\Users\...\Downloads\TWB-master\webmanager\utils.py", line 9, in <module>
    from core.filemanager import FileManager
ModuleNotFoundError: No module named 'core'`

**Comment by stefan2200** [comment]
We've just deployed a fix for that issue. Could you try again and inform us if that fixed the issue?

**Comment by MAHardo** [comment]
Hi Stefan, thank you for your reply. I just upgraded the bot and it works just beautifully, also the telegram bot! Thanks a lot!
